const fetch = require('node-fetch');
const API = 'https://portal.uec.edu.eg/api';

async function main() {
  // Login
  const loginRes = await fetch(`${API}/auth/account-login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ username: 'admin', password: 'Admin123', loginType: 'admin' })
  });
  const loginData = await loginRes.json();
  const token = loginData.token;
  console.log('Logged in as admin');

  const headers = { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` };

  // 1. Supervisors
  console.log('\n--- Uploading Supervisors ---');
  const supData = [
    { supervisorId: 'nmahmoud', password: 'nmahmoud', name: 'Nehad Mahmoud', email: 'nmahmoud@uec.edu.eg' },
    { supervisorId: 'mhamdy', password: 'mhamdy', name: 'Mai Hamdy', email: 'mhamdy@uec.edu.eg' },
    { supervisorId: 'nfawzy', password: 'nfawzy', name: 'Nourhan Fawzy', email: 'nfawzy@uec.edu.eg' },
    { supervisorId: 'sadel', password: 'sadel', name: 'Sara Adel Ahmed', email: 'sadel@uec.edu.eg' },
    { supervisorId: 'ehassan', password: 'ehassan', name: 'Eman Abd El Bary', email: 'ehassan@uec.edu.eg' },
    { supervisorId: 'mhussein', password: 'mhussein', name: 'Mona Raafat', email: 'mhussein@uec.edu.eg' },
    { supervisorId: 'hmohamed', password: 'hmohamed', name: 'Heba Mohamed Awad', email: 'hmohamed@uec.edu.eg' },
    { supervisorId: 'mhesham', password: 'mhesham', name: 'Menna Atallah Hesham', email: 'mhesham@uec.edu.eg' },
    { supervisorId: 'ymohamed', password: 'ymohamed', name: 'Yosra Magdy', email: 'ymohamed@uec.edu.eg' },
    { supervisorId: 'sabdelrahman', password: 'sabdelrahman', name: 'Safaa Mohamed', email: 'sabdelrahman@uec.edu.eg' },
    { supervisorId: 'rabdallah', password: 'rabdallah', name: 'Rasha Abd Allah', email: 'rabdallah@uec.edu.eg' },
    { supervisorId: '11', password: 'Abdelrahman1', name: 'Ahmed Fouaad', email: 'aaaaaa@uec.edu.eg' }
  ];
  let r = await fetch(`${API}/admin/bulkSupervisors`, { method: 'POST', headers, body: JSON.stringify({ data: supData }) });
  let d = await r.json();
  console.log('Supervisors:', d.message);

  // 2. Courses
  console.log('\n--- Uploading Courses ---');
  const coursesData = [
    { courseCode: 'BMS111', courseName: 'Foundations of Normal Human Structure', creditHours: 6, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' },
    { courseCode: 'BMS131', courseName: 'Foundations of Body Function & Biochemistry', creditHours: 5, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' },
    { courseCode: 'BMS141', courseName: 'Foundations of Molecular Biology & Genetics', creditHours: 2, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' },
    { courseCode: 'CMS181', courseName: 'Foundations of Biomedical Research & Biostatistics', creditHours: 2, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' },
    { courseCode: 'CMS111', courseName: 'Foundations of Human Behaviour & Psychology', creditHours: 1, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' },
    { courseCode: 'MED111', courseName: 'Learning & Thinking Skills', creditHours: 1, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' },
    { courseCode: 'LAN112', courseName: 'Critical Thinking', creditHours: 2, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' },
    { courseCode: 'BMS151', courseName: 'Foundations of Pathology', creditHours: 5, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' },
    { courseCode: 'BMS161', courseName: 'Foundations of Pharmacology', creditHours: 5, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' },
    { courseCode: 'BMS171', courseName: 'Foundations of Infections & Infestations', creditHours: 4, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' },
    { courseCode: 'BMS172', courseName: 'Foundations of Immunology', creditHours: 2, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' },
    { courseCode: 'CMS112', courseName: 'Foundations of Clinical Practice: History & Examination/ Basic Life Support', creditHours: 1, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' },
    { courseCode: 'CSE013', courseName: 'Introduction to Information Technology', creditHours: 2, maxSeats: 100, feePerCredit: 3500, faculty: 'Faculty of Medicine' }
  ];
  r = await fetch(`${API}/admin/bulkUpdateCourses`, { method: 'POST', headers, body: JSON.stringify({ data: coursesData }) });
  d = await r.json();
  console.log('Courses:', d.message);

  // 3. Students
  console.log('\n--- Uploading Students ---');
  const studentsData = [
    { studentId: '25100000', password: '25100000', name: 'Amr Attia Ewais', email: 'amr@uec.edu.eg', academicLevel: 'First', supervisorId: '11', faculty: 'Faculty of Medicine' },
    { studentId: '25-100001', password: '25-100001', name: 'Loay Amr Ahmed Adel Mohamed Hussein Mandour', email: 'loay.amr@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100002', password: '25-100002', name: 'Ahmed Medhat Mahmoud Mohamed Bakheet', email: 'ahmed.medhat@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100003', password: '25-100003', name: 'Youssef Yasser Salama Abdelaziz Farag', email: 'youssef.yasser@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100005', password: '25-100005', name: 'Ahmed ElSayed Abdelghani Mohamed Maghrabi', email: 'ahmed.elsayed@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100006', password: '25-100006', name: 'Mohamed Marzouk Hassan Yassin', email: 'mohamed.marzouk@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100007', password: '25-100007', name: 'Youssef Mohamed Ali Hasasn Tolba', email: 'youssef.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100008', password: '25-100008', name: 'Sobhy Ahmed Mohamed Ibrahim Eldaer', email: 'sobhy.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100009', password: '25-100009', name: 'Mahmoud Sameh Ahmed Attia Ghattas', email: 'mahmoud.sameh@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100010', password: '25-100010', name: 'Fedaa-Eleslam Ayman Hafez Mohamed Gabr', email: 'fedaa-eleslam.ayman@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100011', password: '25-100011', name: 'Maryam Mohamed Ismail Abdelazim Saleh', email: 'maryam.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100012', password: '25-100012', name: 'Salma Makarem Mohamed Abdelmoneim Mohamed Bakr', email: 'salma.makarem@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100013', password: '25-100013', name: 'Salma Al-Adl Ibrahim Al- Adl', email: 'salma.al-adl@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100015', password: '25-100015', name: 'Youssef Taj Ibrahim Ismail Gadallah', email: 'youssef.taj@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100017', password: '25-100017', name: 'Zeyad Sameh Ahmed Mohamed Mabrouk', email: 'zeyad.sameh@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100018', password: '25-100018', name: 'Sayf Mahmoud Khalil Abu Nouer', email: 'sayf.mahmoud@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100019', password: '25-100019', name: 'Mahmoud Yasser Mohamed Elshafei', email: 'mahmoud.yasser@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100020', password: '25-100020', name: 'Ezzat Qasem El-Sayed Abdelmegid Rady', email: 'ezzat.qasem@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100021', password: '25-100021', name: 'Sherif Abdullah Abdelsalam Abdullah Ali', email: 'sherif.abdullah@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100022', password: '25-100022', name: 'Mohamed Mostafa Mohamed Abdelazim El- Zoghbi Diab', email: 'mohamed.mostafa@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100023', password: '25-100023', name: 'Abdullah Hani Abdullah Ayub Ibrahim', email: 'abdullah.hani@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100024', password: '25-100024', name: 'Lujain Ahmed Abdelfattah Mohamed Elnabawy Saeid', email: 'lujain.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100025', password: '25-100025', name: 'Basmala Walid Abdelraouf Ibrahim Darwish', email: 'basmala.walid@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100027', password: '25-100027', name: 'Rawda Ahmed Imam Mohamed', email: 'rawda.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100029', password: '25-100029', name: 'Tadros Kerolus Salama Matta Wahba', email: 'tadros.kerolus@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100030', password: '25-100030', name: 'Ahmed Sameh Rizq Ragab Ibrahim', email: 'ahmed.sameh@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100063', password: '25-100063', name: 'Youssef Al-Saied Ezzat Attia Elbahnasy', email: 'youssef.al-saied@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100082', password: '25-100082', name: 'Abdullah Mahmoud Abdelmonem Metwally Mohamed Taee', email: 'abdullah.mahmoud@uec.edu.eg', academicLevel: 'First', supervisorId: 'nmahmoud', faculty: 'Faculty of Medicine' },
    { studentId: '25-100014', password: '25-100014', name: 'Omar Gamal Abdelfattah Zayan', email: 'omar.gamal@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100028', password: '25-100028', name: 'Eyad Ahmed Hassan Mohamed Hassan Khalifa', email: 'eyad.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100031', password: '25-100031', name: 'Eyad Salah Ahmed Shafiq Abdelrahman Ibrahim', email: 'eyad.salah@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100034', password: '25-100034', name: 'Adam Mahmoud Fawzi Riyad Awad', email: 'adam.mahmoud@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100035', password: '25-100035', name: 'Maryam Tamer Mohamed Nassar Ibrahim', email: 'maryam.tamer@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100036', password: '25-100036', name: 'Seif Mohamed Mokhtar Mohamed Mokhtar Daifallah', email: 'seif.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100037', password: '25-100037', name: 'NourEldin Mohamed Safwat Abdelhamid Ahmed', email: 'noureldin.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100038', password: '25-100038', name: 'Ahmed Tawfik Saeed Tawfik Alneklawy', email: 'ahmed.tawfik@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100039', password: '25-100039', name: 'Nada Abdelaal Mohamed Ahmed', email: 'nada.abdelaal@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100041', password: '25-100041', name: 'Adham Sameer Atef El- Desouki El Sayyad', email: 'adham.sameer@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100043', password: '25-100043', name: 'Abdelrahman Bakry Ahmed Saad', email: 'abdelrahman.bakry@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100045', password: '25-100045', name: 'Rahaaf Mohamed Shaban Abu Jabal', email: 'rahaaf.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100047', password: '25-100047', name: 'Ali Mahdi Abdelfattah Ali Farag', email: 'ali.mahdi@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100049', password: '25-100049', name: 'Abdelrahman Mohamed Abdelnabi Abdelfattah Awais', email: 'abdelrahman.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100050', password: '25-100050', name: 'Mohamed Tawfik Shaban Tawfik', email: 'mohamed.tawfik@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100051', password: '25-100051', name: 'Ahmed Emad Abdelaal El Sayed Ibrahim', email: 'ahmed.emad@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100059', password: '25-100059', name: 'Salma Mohamed Elsayed Mohamed Abdelaal', email: 'salma.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100060', password: '25-100060', name: 'Ehsan Ehab Abdelhamid Abdelsalam', email: 'ehsan.ehab@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100061', password: '25-100061', name: 'Nourouz Neshat Mohamed Mahmoud Salama', email: 'nourouz.neshat@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100062', password: '25-100062', name: 'Youssef Mohamed Badr Arafa Ali Karim', email: 'youssef.mohamed2@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100067', password: '25-100067', name: 'Malak Sherif Mohamed Ibrahim Ahmed', email: 'malak.sherif@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100073', password: '25-100073', name: 'Radwa Tarek Abdelmoneim Ahmed', email: 'radwa.tarek@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100080', password: '25-100080', name: 'Salma Ahmed Hassan Mohamed Elshahed', email: 'salma.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100084', password: '25-100084', name: 'Haneen Alaa Abdelmotagaly Haredy', email: 'haneen.alaa@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100091', password: '25-100091', name: 'Youssef Hajjaj Abdelazim', email: 'youssef.hajjaj@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100092', password: '25-100092', name: 'Ammar Yasser Sayed Abdelaal', email: 'ammar.yasser@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100097', password: '25-100097', name: 'Soheila Ahmed Abdelfattah Mohamed Ali Khattab', email: 'soheila.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhamdy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100046', password: '25-100046', name: 'Shaker Ashraf Shaker Youssef', email: 'shaker.ashraf@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100048', password: '25-100048', name: 'Youssef Mahmoud Sayed Youssef', email: 'youssef.mahmoud@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100052', password: '25-100052', name: 'Youssef Mohamed Mahmoud Mostafa Al-Qatt', email: 'youssef.mohamed1@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100053', password: '25-100053', name: 'Hamdy Rafeq Ibrahim Moussa', email: 'hamdy.rafeq@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100055', password: '25-100055', name: 'Mohamed Bahaa Mohamed Sab\'Awy', email: 'mohamed.bahaa@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100056', password: '25-100056', name: 'Mohamed Hani Mohamed Hefny Ali', email: 'mohamed.hani@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100057', password: '25-100057', name: 'Salah Essam Sabah El Din Abdelghani', email: 'salah.essam@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100065', password: '25-100065', name: 'Abdullah Mohamed Anwar Qutb Omara', email: 'abdullah.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100069', password: '25-100069', name: 'Mohamed Mahmoud Shaban Abdelhafiz', email: 'mohamed.mahmoud@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100071', password: '25-100071', name: 'Hisham Ashraf Nabil Sulaiman Hussein', email: 'hisham.ashraf@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100072', password: '25-100072', name: 'Mostafa Sami Mohamed Shehatah Deraz Bayoumi', email: 'mostafa.sami@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100074', password: '25-100074', name: 'Mohamed Ramadan Abdelsalam Mohamed Mostafa', email: 'mohamed.ramadan@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100077', password: '25-100077', name: 'Amer Sruor Gaber Ahmed Abdelhafez', email: 'amer.sruor@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100079', password: '25-100079', name: 'Mohamed Tharwat Qasem Ali Abdallah', email: 'mohamed.tharwat@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100081', password: '25-100081', name: 'Mahmoud Ahmed Saeid Shaheen', email: 'mahmoud.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100083', password: '25-100083', name: 'Abdullah Abdelhakim Mohamed El-Bakri Ismail', email: 'abdullah.abdelhakim@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100086', password: '25-100086', name: 'Ahmed Fouad Sobhi Ahmed Mansour', email: 'ahmed.fouad@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100087', password: '25-100087', name: 'Abdelrahman Mohamed Adel Mohamed Mohamed', email: 'abdelrahman.mohamed1@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100088', password: '25-100088', name: 'Hussien Mohamed Hussein Ibrahim', email: 'hussien.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100089', password: '25-100089', name: 'Amr Mohamed Abdelfattah', email: 'amr.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100090', password: '25-100090', name: 'Ahmed Khaled Mohamed Mohamed Ali', email: 'ahmed.khaled@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100093', password: '25-100093', name: 'Mohamed Mohamed Saudi Abdelhalim', email: 'mohamed.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100171', password: '25-100171', name: 'Waziri Ibrahim Waziri Al-Wardani', email: 'waziri.ibrahim@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100275', password: '25-100275', name: 'Mohamed Hamam Mahmoud Abdelrahman', email: 'mohamed.hamam@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100276', password: '25-100276', name: 'Ahmed Saad Abdel Salam Saad Dawood', email: 'ahmed.saad@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100277', password: '25-100277', name: 'Omar Magdy Fathy Shaaban Abdrabo', email: 'omar.magdy@uec.edu.eg', academicLevel: 'First', supervisorId: 'nfawzy', faculty: 'Faculty of Medicine' },
    { studentId: '25-100094', password: '25-100094', name: 'Ahmed Sabry Mohamed El Sayed', email: 'ahmed.sabry@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100095', password: '25-100095', name: 'Mohamed Yasser Mohamed Mohamed Arab', email: 'mohamed.yasser@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100098', password: '25-100098', name: 'Omar Hosam Eldin Taha Elhakim', email: 'omar.hosam@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100100', password: '25-100100', name: 'Ziad Ibrahim Zein Othman', email: 'ziad.ibrahim@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100101', password: '25-100101', name: 'Mohamed Ahmed Abdelfattah Mohamed', email: 'mohamed.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100102', password: '25-100102', name: 'Reham Adel Attia Mohamed', email: 'reham.adel@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100103', password: '25-100103', name: 'Alaa Mohamed Ahmed Mehallel', email: 'alaa.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100105', password: '25-100105', name: 'Mohamed Fayed Noeman Mohamed Abu Ghali', email: 'mohamed.fayed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100106', password: '25-100106', name: 'Shahd Islam Ahmed Mohamed Mostafa Zeyara', email: 'shahd.islam@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100107', password: '25-100107', name: 'Abdullah Mosbah Hamdy Ibrahim Elkhadargy', email: 'abdullah.mosbah@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100108', password: '25-100108', name: 'Hassan Sami Hassan Mohamed Hassan', email: 'hassan.sami@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100109', password: '25-100109', name: 'Khaled Yassin Hashim Abdelaziz Mohamed', email: 'khaled.yassin@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100114', password: '25-100114', name: 'Omar Atef Ahmed Ali', email: 'omar.atef@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100115', password: '25-100115', name: 'ElSayed Essam Ahmed Abdelkarim Ahmed', email: 'elsayed.essam@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100116', password: '25-100116', name: 'Roufida Ahmed Mahrous Abdo Khalaf', email: 'roufida.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100119', password: '25-100119', name: 'Omar Mohamed Ahmed Sami Mohamed Elshahawy', email: 'omar.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100121', password: '25-100121', name: 'NourEldin Ahmed Abdelaziz Mohamed Al-Shehaly', email: 'noureldin.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100122', password: '25-100122', name: 'Amr Yasser Abdelaziz Abdelazim Ahmed', email: 'amr.yasser@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100126', password: '25-100126', name: 'Eman Behjat Ahmed Ali Ibrahim', email: 'eman.behjat@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100127', password: '25-100127', name: 'Mayar Mostafa Mohamed Elhanafi Ismail', email: 'mayar.mostafa@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100128', password: '25-100128', name: 'Hana Hani Hassan Mahmoud Yaqoub', email: 'hana.hani@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100130', password: '25-100130', name: 'Abdelmenaem Abdelatif Abdelaziz Hassan Ahmed', email: 'abdelmenaem.abdelatif@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100133', password: '25-100133', name: 'Yara Mohamed Ismail Alhusseiny Ibrahim', email: 'yara.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100135', password: '25-100135', name: 'Amr AbuEl-Yazeed Abdelfattah Abu El-Yazeed Taha', email: 'amr.abuel-yazeed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100136', password: '25-100136', name: 'Youssef Mohamed Anwar Fanjari', email: 'youssef.mohamed3@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100138', password: '25-100138', name: 'Omar Mohamed Mohamed Abdelwahab Salama Elgharbawy', email: 'omar.mohamed1@uec.edu.eg', academicLevel: 'First', supervisorId: 'ehassan', faculty: 'Faculty of Medicine' },
    { studentId: '25-100139', password: '25-100139', name: 'Mohamed Mahdi Mahmoud Abdelsalam', email: 'mohamed.mahdi@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100140', password: '25-100140', name: 'Abdelaziz Ali Saad Atiwa', email: 'abdelaziz.ali@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100141', password: '25-100141', name: 'Abdelrahman Sabry Elsayed Hassanein', email: 'abdelrahman.sabry@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100142', password: '25-100142', name: 'Abdelrahman Saeed Ali Abdullah Pasha', email: 'abdelrahman.saeed@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100143', password: '25-100143', name: 'Youssef Alaa Shaaban Sayed Saber', email: 'youssef.alaa@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100144', password: '25-100144', name: 'Omar Hassan Abdelrahim Mohamed Moussa', email: 'omar.hassan@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100145', password: '25-100145', name: 'Afnan Badr Ismail Abdelrahim', email: 'afnan.badr@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100146', password: '25-100146', name: 'Haneen Hisham El Sayed Sebaei El Sayed', email: 'haneen.hisham@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100147', password: '25-100147', name: 'ShamsEldin Saied Shams Eldin Mahmoud', email: 'shamseldin.saied@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100149', password: '25-100149', name: 'Abdelrahman Yasser Gomaa Mahmoud Elmasry', email: 'abdelrahman.yasser@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100150', password: '25-100150', name: 'Ahmed Mohamed Mahmoud Ahmed El Masry', email: 'ahmed.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100151', password: '25-100151', name: 'Saied Sabry Saied Hashim Tahoun', email: 'saied.sabry@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100153', password: '25-100153', name: 'Mohamed Khaled Ahmed Kamal', email: 'mohamed.khaled@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100154', password: '25-100154', name: 'Adham Mohamed Khalil El Taher Hassan', email: 'adham.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100155', password: '25-100155', name: 'Mona Ashraf Ibrahim Mohamed El Moghazi', email: 'mona.ashraf@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100156', password: '25-100156', name: 'Abdelrahman Fawzi Fathi', email: 'abdelrahman.fawzi@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100157', password: '25-100157', name: 'Amr Khaled Mohamed Ibrahim Farag', email: 'amr.khaled@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100159', password: '25-100159', name: 'Mohab Abdullah Mohamed Ahmed Ahmed', email: 'mohab.abdullah@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100160', password: '25-100160', name: 'Abdullah Ibrahim Abdullah Ibrahim Ahmed', email: 'abdullah.ibrahim@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100161', password: '25-100161', name: 'Omar Mohamed Gomaa Ahmed Ahmed', email: 'omar.mohamed2@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100162', password: '25-100162', name: 'Jana Osama Mohamed Mohamed', email: 'jana.osama@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100163', password: '25-100163', name: 'Omar Sabry Abdelaziz Khedr Selim', email: 'omar.sabry@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100164', password: '25-100164', name: 'Ahmed Mohamed Saleh Abdelrahman', email: 'ahmed.mohamed1@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100165', password: '25-100165', name: 'Youssef Nabil Fathy Mohamed Abdelghani Al-Souli', email: 'youssef.nabil@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100166', password: '25-100166', name: 'Tamar Ehab Mohamed Abbas Abuelela', email: 'tamar.ehab@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100167', password: '25-100167', name: 'Toka Mohamed Abdelsalam Mohamed El Rouiny', email: 'toka.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100168', password: '25-100168', name: 'Islam Abdelsattar Abdelhamid Ahmed', email: 'islam.abdelsattar@uec.edu.eg', academicLevel: 'First', supervisorId: 'mhussein', faculty: 'Faculty of Medicine' },
    { studentId: '25-100076', password: '25-100076', name: 'Rahaf Hany Salama Marei Salama', email: 'rahaf.hany@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100085', password: '25-100085', name: 'Jana Mohamed Ahmed Mohamed Awadallah', email: 'jana.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100169', password: '25-100169', name: 'Sara Ahmed Galal Ali', email: 'sara.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100170', password: '25-100170', name: 'Mohamed Shoukry Mohamed Desouky Abu Al-Majd', email: 'mohamed.shoukry@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100173', password: '25-100173', name: 'Maryam AbuBakr Mohamed Nafadi', email: 'maryam.abubakr@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100174', password: '25-100174', name: 'Menatallah AbuBakr Mohamed Nafadi', email: 'menatallah.abubakr@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100175', password: '25-100175', name: 'Mohamed Ahmed Ahmed Hamed Elhusseini', email: 'mohamed.ahmed1@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100176', password: '25-100176', name: 'Samar Essam Farouk Mohamed Mohamed', email: 'samar.essam@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100177', password: '25-100177', name: 'Karim Maher Abd Elhamed Dekhil', email: 'karim.maher@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100178', password: '25-100178', name: 'Aya Mahmoud Abdelmoghny Abdullah Dowidar', email: 'aya.mahmoud@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100179', password: '25-100179', name: 'Mohamed Ehab Mohamed Fahmy Darwish', email: 'mohamed.ehab@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100181', password: '25-100181', name: 'Mostafa Ibrahim Mohamed El- Alawi', email: 'mostafa.ibrahim@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100182', password: '25-100182', name: 'Miryam Majed Mohamed Ibrahim', email: 'miryam.majed@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100183', password: '25-100183', name: 'Mohamed EmadElDin Mohamed Hassan Mostafa', email: 'mohamed.emadeldin@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100184', password: '25-100184', name: 'Mazen Mustafa Mohamedin Mohamed Mohamedin', email: 'mazen.mustafa@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100185', password: '25-100185', name: 'Mohammad Ahmed Mahmoud Gouda Omar', email: 'mohammad.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100186', password: '25-100186', name: 'Mohamed Ezzat Mohamed Elsayed Salama', email: 'mohamed.ezzat@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100187', password: '25-100187', name: 'Mohamed Ahmed Nasr Eldin Mohamed Ahmed', email: 'mohamed.ahmed2@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100188', password: '25-100188', name: 'Joy Osama Gurguis Ayad Qliny', email: 'joy.osama@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100189', password: '25-100189', name: 'Abdullah Nader Abdullah Abduljawad Al-Oteiwy', email: 'abdullah.nader@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100190', password: '25-100190', name: 'Omnia Emad Ahmed Ghobbashi Abdelmaksoud', email: 'omnia.emad@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100191', password: '25-100191', name: 'Haneen Haitham Nagi Abdelmajeed Amer', email: 'haneen.haitham@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100278', password: '25-100278', name: 'Ibrahim Haitham Mohammed El Araby Hassan', email: 'ibrahim.haitham@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100279', password: '25-100279', name: 'Shahd Moustafa Mohamed Fathy Moustafa Mohamed', email: 'shahd.moustafa@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100281', password: '25-100281', name: 'Mohamed Goda Rady Ahmed Mohamed', email: 'mohamed.goda@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100282', password: '25-100282', name: 'Ahmed Salim Mohammed Mahmoud Alshaer', email: 'ahmed.salim@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100284', password: '25-100284', name: 'Abdallah Ahmed Mahmoud Ahmed Hassan', email: 'abdallah.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'hmohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100192', password: '25-100192', name: 'Mahmoud Mazhar Abu Zaid Ali Abdel-Ghani', email: 'mahmoud.mazhar@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100193', password: '25-100193', name: 'Mohamed Khamis Abdelaal Khamis', email: 'mohamed.khamis@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100194', password: '25-100194', name: 'Mohamed Omar Mustafa Taha El Akhtabi', email: 'mohamed.omar@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100195', password: '25-100195', name: 'Abdelrahman Ahmed Hassan Mohamed Abuzeid', email: 'abdelrahman.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100196', password: '25-100196', name: 'Mostafa Mohamed Mostafa Gouda', email: 'mostafa.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100197', password: '25-100197', name: 'Jana Ali Abdel-Razek Ahmed Abdel-Salam', email: 'jana.ali@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100198', password: '25-100198', name: 'Mohamed Saeed Jalal Mohamed Abdullah Hamid', email: 'mohamed.saeed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100199', password: '25-100199', name: 'Jana Hazem Salah El Din Soliman Al-Shami', email: 'jana.hazem@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100200', password: '25-100200', name: 'Ayten Hassan Ahmed Taher', email: 'ayten.hassan@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100201', password: '25-100201', name: 'Youssef Hossam Awad Abdelkader Abdelgalil', email: 'youssef.hossam@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100202', password: '25-100202', name: 'Mahmoud Mohamed Hatem Ammar Moussa', email: 'mahmoud.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100203', password: '25-100203', name: 'Sawsan Yasser Mohamed Abdelrahman', email: 'sawsan.yasser@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100204', password: '25-100204', name: 'Fatema Mohamed Samy Mahmoud Nassar', email: 'fatema.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100205', password: '25-100205', name: 'Judi Mohamed Mamdouh Mohamed Mahmoud', email: 'judi.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100206', password: '25-100206', name: 'Mohamed Wageh Abdelrahman Youssef Ismail', email: 'mohamed.wageh@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100207', password: '25-100207', name: 'Abdallah Hazem Hafez Allam', email: 'abdallah.hazem@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100208', password: '25-100208', name: 'Romaysaa Mohsen Shawky Abu Zeid', email: 'romaysaa.mohsen@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100209', password: '25-100209', name: 'Mohamed El-Husseini Abdelaziz Abdelaal Badr', email: 'mohamed.el-husseini@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100210', password: '25-100210', name: 'Seham Mahmoud Abu Leila Ahmed', email: 'seham.mahmoud@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100211', password: '25-100211', name: 'Sondos Sami Mohamed Abdel-Kader Abdelhadi', email: 'sondos.sami@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100212', password: '25-100212', name: 'Abdelrahman Mohie Ahmed Abdelaal', email: 'abdelrahman.mohie@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100213', password: '25-100213', name: 'Ammar Saeed Abdelhafeez Omar El Deeb', email: 'ammar.saeed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100214', password: '25-100214', name: 'Nourhan Hamed Mahmoud Ahmed', email: 'nourhan.hamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100215', password: '25-100215', name: 'Mariam Mostafa Mohamed Mostafa', email: 'mariam.mostafa@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100216', password: '25-100216', name: 'Jana Reda Mustafa Salama Mustafa', email: 'jana.reda@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100217', password: '25-100217', name: 'Amal Nasr Saleh Attia Zaied', email: 'amal.nasr@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100218', password: '25-100218', name: 'Rawan Karim Abdelbar Abdel-Razek El Ajami', email: 'rawan.karim@uec.edu.eg', academicLevel: 'First', supervisorId: 'ymohamed', faculty: 'Faculty of Medicine' },
    { studentId: '25-100219', password: '25-100219', name: 'Hoda Mohamed Ibrahim Mustafa Al-Naqidi', email: 'hoda.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100220', password: '25-100220', name: 'Ammar Ramadan Shehata Daiief', email: 'ammar.ramadan@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100221', password: '25-100221', name: 'Omar Mohammed Mohammed Hussein Abdellah', email: 'omar.mohammed@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100222', password: '25-100222', name: 'Ali Elhussein Ali Sayed', email: 'ali.elhussein@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100223', password: '25-100223', name: 'Abdelwhab Kamal Abdelwhab Mohammed', email: 'abdelwhab.kamal@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100224', password: '25-100224', name: 'Maryem yasser abdelrasol abdelmotlaa Mohamed', email: 'maryem.yasser@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100225', password: '25-100225', name: 'Esraa Khaled Abdalftah Hassan Elnagar', email: 'esraa.khaled@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100226', password: '25-100226', name: 'Israa Hassan Sayed Mohamed', email: 'israa.hassan@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100227', password: '25-100227', name: 'Essam Omar Abdallah Mohamed Hassan', email: 'essam.omar@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100228', password: '25-100228', name: 'Noha Taha Shehata Ahmed', email: 'noha.taha@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100230', password: '25-100230', name: 'Berihan Ahmed Ibrahim Abdelrazek Mohamed', email: 'berihan.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100231', password: '25-100231', name: 'Ibrahim Amer Ibrahim Abdelkhalek Mostafa', email: 'ibrahim.amer@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100232', password: '25-100232', name: 'Adham Ahmed Abdelmegid Abdelmegid Abd-Rabo', email: 'adham.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100233', password: '25-100233', name: 'Hamza Mohamed Abdelhalim Bahnasawy Abdelhalim', email: 'hamza.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100234', password: '25-100234', name: 'Fares Ramadan Mohamed Mahmoud Abdelgalil', email: 'fares.ramadan@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100235', password: '25-100235', name: 'Moataz Alaa Abdelaal Hassan', email: 'moataz.alaa@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100236', password: '25-100236', name: 'Mazen Ahmed Mohammad Ahmed Hassan', email: 'mazen.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100238', password: '25-100238', name: 'Mennah Allah Tamer Sabry Ibrahim Elgamel', email: 'mennah.allah@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100239', password: '25-100239', name: 'Ahmed Abdelsabour Abdallah Mohamed Soliman', email: 'ahmed.abdelsabour@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100240', password: '25-100240', name: 'Mohamed ElSayed Mohamed Hassan Abdelaal', email: 'mohamed.elsayed@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100241', password: '25-100241', name: 'Ibrahim Nasr Eldin Elish Marwan', email: 'ibrahim.nasr@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100242', password: '25-100242', name: 'Abdelrahman Mahmoud Mohamed Ali', email: 'abdelrahman.mahmoud@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100243', password: '25-100243', name: 'Mohamed Ahmed Mohamed Abdelkerim Hassan', email: 'mohamed.ahmed3@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100244', password: '25-100244', name: 'Youssef Ahmed Nagaty Abdullah Moussa', email: 'youssef.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100245', password: '25-100245', name: 'Abdelrahman Sabry Fawzy Mohamed Rabie', email: 'abdelrahman.sabry1@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100246', password: '25-100246', name: 'Lina Abdrabo Saleh Ibrahim Rageh', email: 'lina.abdrabo@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100248', password: '25-100248', name: 'Manar Abdelbaset Saeed Abdelbaset Moustafa', email: 'manar.abdelbaset@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100285', password: '25-100285', name: 'Mera Osman Farag Mohamed', email: 'mera.osman@uec.edu.eg', academicLevel: 'First', supervisorId: 'sabdelrahman', faculty: 'Faculty of Medicine' },
    { studentId: '25-100249', password: '25-100249', name: 'Karam Abdallah Elmaghzy Ibrahim Genidi', email: 'karam.abdallah@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100250', password: '25-100250', name: 'Haidi Ramadan Abu El-gheit Mahmoud Shaaban', email: 'haidi.ramadan@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100251', password: '25-100251', name: 'Abdelrahman Elsayed Fathy Moslehi Ramadan', email: 'abdelrahman.elsayed@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100252', password: '25-100252', name: 'Ahmed Eid Hagrasi Ali Ibrahim', email: 'ahmed.eid@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100253', password: '25-100253', name: 'Nermeen Salah Saber Saad Eldin', email: 'nermeen.salah@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100254', password: '25-100254', name: 'Ismail alqlaly AbdElmoiz Sayed Ahmed', email: 'ismail.alqlaly@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100255', password: '25-100255', name: 'Mina Girgis Sanad Girgis Abdelshaheed', email: 'mina.girgis@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100256', password: '25-100256', name: 'Islam Ahmed Diab Ali Abdullah', email: 'islam.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100257', password: '25-100257', name: 'Ethar Mohamed Abdelfatah Mohamed Elsaidi', email: 'ethar.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100258', password: '25-100258', name: 'Yousef Ayman Kamal Mohamed Saleh', email: 'yousef.ayman@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100260', password: '25-100260', name: 'Saad Mohamed Saad Abdelaziz Attia', email: 'saad.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100262', password: '25-100262', name: 'Mohamed Ahmed Sayed Qurni Hussein El-Banna', email: 'mohamed.ahmed4@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100263', password: '25-100263', name: 'Jana Ahmed Mohamed Mohamed Ahmed El -Maalouf', email: 'jana.ahmed@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100264', password: '25-100264', name: 'Ziad Emad Anwar Mohamed', email: 'ziad.emad@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100265', password: '25-100265', name: 'Rawan Shaban Gomaa Elsayed khalifa', email: 'rawan.shaban@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100266', password: '25-100266', name: 'Esraa Hussein Hassan Abdullah Abdelaal', email: 'esraa.hussein@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100267', password: '25-100267', name: 'Hanin Mostafa Ahmed Ali Abdelmahdi', email: 'hanin.mostafa@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100268', password: '25-100268', name: 'Mahmoud Fakhry Abdel Razzaq Khaled', email: 'mahmoud.fakhry@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100269', password: '25-100269', name: 'Abdelaziz Medhat Abdelaziz Mahmoud Elnewahy', email: 'abdelaziz.medhat@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100270', password: '25-100270', name: 'Keroles Amgad Wasfy Youssef Shaker', email: 'keroles.amgad@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100271', password: '25-100271', name: 'Mahmoud Abdellatif Mahmoud Abdellatif', email: 'mahmoud.abdellatif@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100272', password: '25-100272', name: 'Mohamed Assem Mohamed Elsaid Eliwa', email: 'mohamed.assem@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100273', password: '25-100273', name: 'Hana Salah Eldin Abdel Rafee Mohamed', email: 'hana.salah@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100274', password: '25-100274', name: 'Raghdaa Mokhtar Mohamed Amin Mohamed Mukhtar Maslhy', email: 'raghdaa.mokhtar@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100280', password: '25-100280', name: 'Gana Mohamed Abdelhakem Mohamed Amer', email: 'gana.mohamed@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' },
    { studentId: '25-100283', password: '25-100283', name: 'Ahmed Nashaat Abdelmonem Ahmed Abdelhamid', email: 'ahmed.nashaat@uec.edu.eg', academicLevel: 'First', supervisorId: 'rabdallah', faculty: 'Faculty of Medicine' }
  ];
  r = await fetch(`${API}/admin/bulkAssignSupervisors`, { method: 'POST', headers, body: JSON.stringify({ data: studentsData }) });
  d = await r.json();
  console.log('Students:', d.message);

  // 4. Failed Courses
  console.log('\n--- Uploading Failed Courses ---');
  const failedData = [
    { studentId: '25100000', courseCode: 'BMS111' },
    { studentId: '25100000', courseCode: 'BMS131' },
    { studentId: '25100000', courseCode: 'BMS141' }
  ];
  r = await fetch(`${API}/admin/bulkFailedCourses`, { method: 'POST', headers, body: JSON.stringify({ data: failedData }) });
  d = await r.json();
  console.log('Failed Courses:', d.message);

  console.log('\n=== ALL DONE ===');
}

main().catch(e => console.error(e));
